export const authCostanti = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
}

export const utenteCostanti = {
    UTENTE_REGISTRAZIONE_REQUEST:'UTENTE_REGISTRAZIONE_REQUEST',
    UTENTE_REGISTRAZIONE_SUCCESS:'UTENTE_REGISTRAZIONE_SUCCESS',
    UTENTE_REGISTRAZIONE_FAILURE:'UTENTE_REGISTRAZIONE_FAILURE'
}
export const partiteCostanti = {
    ADD_NEW_PARTITE_REQUEST:'ADD_NEW_PARTITE_REQUEST',
    ADD_NEW_PARTITE_SUCCESS:'ADD_NEW_PARTITE_SUCCESS',
    ADD_NEW_PARTITE_FAILURE:'ADD_NEW_PARTITE_FAILURE',
    UPDATE_PARTITE_REQUEST:'UPDATE_PARTITE_REQUEST',
    UPDATE_PARTITE_SUCCESS:'UPDATE_PARTITE_SUCCESS',
    UPDATE_PARTITE_FAILURE:'UPDATE_PARTITE_FAILURE',
    GET_ALL_PARTITE_REQUEST:'GET_ALL_PARTITE_REQUEST',
    GET_ALL_PARTITE_SUCCESS:'GET_ALL_PARTITE_SUCCESS',
    GET_ALL_PARTITE_FAILURE:'GET_ALL_PARTITE_FAILURE',
    DELETE_PARTITE_BY_ID_REQUEST:'DELETE_PARTITE_BY_ID_REQUEST',
    DELETE_PARTITE_BY_ID_SUCCESS:'DELETE_PARTITE_BY_ID_SUCCESS',
    DELETE_PARTITE_BY_ID_FAILURE:'DELETE_PARTITE_BY_ID_FAILURE'

}
export const stadiCostanti = {
    ADD_NEW_STADIO_REQUEST:'ADD_NEW_STADIO_REQUEST',
    ADD_NEW_STADIO_SUCCESS:'ADD_NEW_STADIO_SUCCESS',
    ADD_NEW_STADIO_FAILURE:'ADD_NEW_STADIO_FAILURE',
    UPDATE_STADIO_REQUEST:'UPDATE_STADIO_REQUEST',
    UPDATE_STADIO_SUCCESS:'UPDATE_STADIO_SUCCESS',
    UPDATE_STADIO_FAILURE:'UPDATE_STADIO_FAILURE',
    GET_ALL_STADIO_REQUEST:'GET_ALL_STADIO_REQUEST',
    GET_ALL_STADIO_SUCCESS:'GET_ALL_STADIO_SUCCESS',
    GET_ALL_STADIO_FAILURE:'GET_ALL_STADIO_FAILURE',
    DELETE_STADIO_BY_ID_REQUEST:'DELETE_STADIO_BY_ID_REQUEST',
    DELETE_STADIO_BY_ID_SUCCESS:'DELETE_STADIO_BY_ID_SUCCESS',
    DELETE_STADIO_BY_ID_FAILURE:'DELETE_STADIO_BY_ID_FAILURE'
}
export const initialDataCostanti = {
    GET_ALL_INITIAL_DATA_REQUEST: "GET_ALL_INITIAL_DATA_REQUEST",
    GET_ALL_INITIAL_DATA_SUCCESS: "GET_ALL_INITIAL_DATA_SUCCESS",
    GET_ALL_INITIAL_DATA_FAILURE: "GET_ALL_INITIAL_DATA_FAILURE",
};

export const clientiCostanti = {
    GET_ALL_CLIENTI_REQUEST:'GET_ALL_CLIENTI_REQUEST',
    GET_ALL_CLIENTI_SUCCESS:'GET_ALL_CLIENTI_SUCCESS',
    GET_ALL_CLIENTI_FAILURE:'GET_ALL_CLIENTI_FAILURE',
    DELETE_CLIENTI_BY_ID_REQUEST:'DELETE_CLIENTI_BY_ID_REQUEST',
    DELETE_CLIENTI_BY_ID_SUCCESS:'DELETE_CLIENTI_BY_ID_SUCCESS',
    DELETE_CLIENTI_BY_ID_FAILURE:'DELETE_CLIENTI_BY_ID_FAILURE',
}
export const ordiniCostanti = {
    GET_ALL_ORDINI_REQUEST:'GET_ALL_ORDINI_REQUEST',
    GET_ALL_ORDINI_SUCCESS:'GET_ALL_ORDINI_SUCCESS',
    GET_ALL_ORDINI_FAILURE:'GET_ALL_ORDINI_FAILURE',
    DELETE_ORDINI_BY_ID_REQUEST:'DELETE_ORDINI_BY_ID_REQUEST',
    DELETE_ORDINI_BY_ID_SUCCESS:'DELETE_ORDINI_BY_ID_SUCCESS',
    DELETE_ORDINI_BY_ID_FAILURE:'DELETE_ORDINI_BY_ID_FAILURE',
}
export const categorieCostanti = {
    ADD_NEW_CATEGORIE_REQUEST:'ADD_NEW_CATEGORIE_REQUEST',
    ADD_NEW_CATEGORIE_SUCCESS:'ADD_NEW_CATEGORIE_SUCCESS',
    ADD_NEW_CATEGORIE_FAILURE:'ADD_NEW_CATEGORIE_FAILURE',
    UPDATE_CATEGORIE_REQUEST:'UPDATE_CATEGORIE_REQUEST',
    UPDATE_CATEGORIE_SUCCESS:'UPDATE_CATEGORIE_SUCCESS',
    UPDATE_CATEGORIE_FAILURE:'UPDATE_CATEGORIE_FAILURE',
    GET_ALL_CATEGORIE_REQUEST:'GET_ALL_CATEGORIE_REQUEST',
    GET_ALL_CATEGORIE_SUCCESS:'GET_ALL_CATEGORIE_SUCCESS',
    GET_ALL_CATEGORIE_FAILURE:'GET_ALL_CATEGORIE_FAILURE',
    DELETE_CATEGORIE_REQUEST:'DELETE_CATEGORIE_REQUEST',
    DELETE_CATEGORIE_SUCCESS:'DELETE_CATEGORIE_SUCCESS',
    DELETE_CATEGORIE_FAILURE:'DELETE_CATEGORIE_FAILURE'

}